services:
  - type: web
    name: eventflow
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: JWT_SECRET
        value: Um4v8rEG10dbJTtIqup4Xt7b48WnmvKDCQsJqiBmTynORmQAmunMT0t1MBK2/Awe
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SQLITE_DATABASE_URL
        value: file:./dev.db
